### ISSUE TITLE
Calculator's extra options are inacessible

### ISSUE THREAD

**Issue by nmcain** [dahliaOS/calculator#1]
**Describe the bug**
The additional options in the calculator application do not work

**What kind of a bug is it?**
Visual/application bug

**To Reproduce**
Open the calculator application
Attempt to open the menu
It does not open

**Expected behavior**
The green menu should open 

**Screenshots**
n/a
**Desktop (please complete the following information):**
 - OS: affects all
 - Device: Acer Chromebook 14

**dahliaOS build version**
Prerelease

**Additional context**

**Comment by bleonard252** [comment]
This was fixed in 6ff1543. Closing.
