### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by IzzySoft** [dahliaOS/calculator#6]
As you might have missed notifications from GitLab: can you please [check here](https://gitlab.com/fdroid/rfp/-/issues/1995#note_890641009)? There's a minor mis-spelling that needs to be fixed before your app can be included. Would be a pity if that keeps it from being listed :wink:

**Comment by IzzySoft** [comment]
Thanks a lot! Now we just need to get the build recipe ready (see "over there") and then a correponding merge request can be opened with the YAML.

**Comment by julianfairfax** [comment]
Out of interest, why is this the only dalihaOS app on F-Droid?

**Comment by nmcain** [comment]
Currently, Calculator is the most complete app in our lineup. The other issue limiting the availability of our apps on other platforms is that a ton of them are Linux platform specific, the only way to get them running would be to effectively rewrite them for Android using its APIs.
